services:
  - type: static_site
    name: frontend-lacasadifrango
    env: node
    buildCommand: npm install && npm run build
    publishPath: dist
    routes:
      - type: rewrite
        source: /* 
        destination: /index.html
